pl1 = input('Digite algo ')
print('O tipo primitivo desse valor {}'.format(type(pl1)))
print('Só tem espaços?', pl1.isspace())
print('É maiusculas?', pl1.isupper())
print('É um número?', pl1.isnumeric())
print('É alfabeto?', pl1.isalpha())
print('È alfanumerico?', pl1.isalnum())
print('É letras minusculas?', pl1.islower())
print('Esta capitalizada?', pl1.istitle())
