nome = str(input('Digite seu nome completo: ')).strip()
print ('Analisando seu nome...')
print ('Seu nome em maiúsculas é {}'.format(nome.upper()))
print ('Seu nome em minúsculas é {}'.format(nome.lower()))
print ('O seu nome completo tem ao todo {} letras.'.format(len(nome)-nome.count(' ')))
print ('No seu primeiro nome tem {} letras.'.format(nome.find(' ')))